# Pines y estandares de niveles logicos
#Clock
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports clock_50_i]

#Leds y Botones
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports LED1]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports LED2]
#set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports LED2] #compartido BTN
#set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports BTN] #compartido LED
#set_property PULLUP true [get_ports BTN]

#Keyboard and mouse
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33 PULLUP true} [get_ports ps2_clk_io]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33 PULLUP true} [get_ports ps2_data_io]
#mouse clk
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33 PULLUP true} [get_ports ps2_pin6_io] 
#mouse data
set_property -dict {PACKAGE_PIN N5 IOSTANDARD LVCMOS33 PULLUP true} [get_ports ps2_pin2_io] 

# Video output
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports hsync_o]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports vsync_o]

set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[0]]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[1]]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[2]]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[3]]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[4]]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[5]]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[6]]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports rgb_b_o[7]]

set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[0]]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[1]]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[2]]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[3]]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[4]]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[5]]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[6]]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports rgb_g_o[7]]

set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[0]]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[1]]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[2]]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[3]]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[4]]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[5]]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[6]]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports rgb_r_o[7]]


#Audio
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports audioext_l_o]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports audioext_r_o]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33}  [get_ports ear_port_i]

set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS33} [get_ports i2s_bclk_o]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports i2s_lrclk_o]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS33} [get_ports i2s_dout_o]


#Joystick
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports joy_select]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports joy_load]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports joy_data]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports joy_clk]


##JAMMA
#set_property PACKAGE_PIN AB5 [get_ports jamma_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports jamma_clk]
#set_property PACKAGE_PIN AA4 [get_ports jamma_load_n]
#set_property IOSTANDARD LVCMOS33 [get_ports jamma_load_n]
#set_property PACKAGE_PIN AA6 [get_ports jamma_data]
#set_property IOSTANDARD LVCMOS33 [get_ports jamma_data]

#SRAM
set_property IOSTANDARD LVCMOS33 [get_ports ram_*]
set_property SLEW SLOW [get_ports ram_*]
set_property PACKAGE_PIN U18 [get_ports {ram_addr_o[0]}]
set_property PACKAGE_PIN AB18 [get_ports {ram_addr_o[1]}]
set_property PACKAGE_PIN P15 [get_ports {ram_addr_o[2]}]
set_property PACKAGE_PIN T18 [get_ports {ram_addr_o[3]}]
set_property PACKAGE_PIN R17 [get_ports {ram_addr_o[4]}]
set_property PACKAGE_PIN P14 [get_ports {ram_addr_o[5]}]
set_property PACKAGE_PIN AB3 [get_ports {ram_addr_o[6]}]
set_property PACKAGE_PIN Y3 [get_ports {ram_addr_o[7]}]
set_property PACKAGE_PIN R14 [get_ports {ram_addr_o[8]}]
set_property PACKAGE_PIN T3 [get_ports {ram_addr_o[9]}]
set_property PACKAGE_PIN P16 [get_ports {ram_addr_o[10]}]
set_property PACKAGE_PIN AA3 [get_ports {ram_addr_o[11]}]
set_property PACKAGE_PIN P17 [get_ports {ram_addr_o[12]}]
set_property PACKAGE_PIN AB2 [get_ports {ram_addr_o[13]}]
set_property PACKAGE_PIN AA18 [get_ports {ram_addr_o[14]}]
set_property PACKAGE_PIN Y2 [get_ports {ram_addr_o[15]}]
set_property PACKAGE_PIN Y1 [get_ports {ram_addr_o[16]}]
set_property PACKAGE_PIN W1 [get_ports {ram_addr_o[17]}]
set_property PACKAGE_PIN V3 [get_ports {ram_addr_o[18]}]
set_property PACKAGE_PIN G2 [get_ports {ram_addr_o[19]}]

set_property PACKAGE_PIN N17 [get_ports {ram_data_io[0]}]
set_property PACKAGE_PIN AA5 [get_ports {ram_data_io[1]}]
set_property PACKAGE_PIN N14 [get_ports {ram_data_io[2]}]
set_property PACKAGE_PIN N13 [get_ports {ram_data_io[3]}]
set_property PACKAGE_PIN R16 [get_ports {ram_data_io[4]}]
set_property PACKAGE_PIN AA1 [get_ports {ram_data_io[5]}]
set_property PACKAGE_PIN AB1 [get_ports {ram_data_io[6]}]
set_property PACKAGE_PIN U3 [get_ports {ram_data_io[7]}]
set_property PACKAGE_PIN N2 [get_ports {ram_data_io[8]}]
set_property PACKAGE_PIN P2 [get_ports {ram_data_io[9]}]
set_property PACKAGE_PIN P1 [get_ports {ram_data_io[10]}]
set_property PACKAGE_PIN R1 [get_ports {ram_data_io[11]}]
set_property PACKAGE_PIN K6 [get_ports {ram_data_io[12]}]
set_property PACKAGE_PIN L1 [get_ports {ram_data_io[13]}]
set_property PACKAGE_PIN M1 [get_ports {ram_data_io[14]}]
set_property PACKAGE_PIN K4 [get_ports {ram_data_io[15]}]

set_property PACKAGE_PIN N15 [get_ports ram_we_n_o]
set_property PACKAGE_PIN E1 [get_ports ram_oe_n_o]
set_property PACKAGE_PIN U20 [get_ports ram_ub_n_o]
set_property PACKAGE_PIN N4 [get_ports ram_lb_n_o]

#SD
set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVCMOS33 PULLUP true} [get_ports sd_miso_i]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports sd_mosi_o]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports sd_sclk_o]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports sd_cs0_n_o]


##Flash SPI
#set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports flash_cs_n_o]
#                                #L12/T4
#set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS33} [get_ports flash_sclk_o] 
#set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVCMOS33} [get_ports flash_mosi_o]
#set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33 PULLUP true} [get_ports flash_miso_i]
#set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33} [get_ports flash_wp_o ]
#set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports flash_hold_o]

#
# SDRAM signals
#
#set_property PACKAGE_PIN G20 [get_ports SDCLK0]
#set_property IOSTANDARD LVCMOS33 [get_ports SDCLK0]
#set_property PACKAGE_PIN H22 [get_ports SDCKE0]
#set_property IOSTANDARD LVCMOS33 [get_ports SDCKE0]

#set_property PACKAGE_PIN L21 [get_ports DQM[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports DQM[1]]
#set_property PACKAGE_PIN M18 [get_ports DQM[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports DQM[0]]

#set_property PACKAGE_PIN L18 [get_ports CAS]
#set_property IOSTANDARD LVCMOS33 [get_ports CAS]
#set_property PACKAGE_PIN K19 [get_ports RAS]
#set_property IOSTANDARD LVCMOS33 [get_ports RAS]
#set_property PACKAGE_PIN J17 [get_ports SDWE]
#set_property IOSTANDARD LVCMOS33 [get_ports SDWE]
#set_property PACKAGE_PIN N22 [get_ports SDCS0]
#set_property IOSTANDARD LVCMOS33 [get_ports SDCS0]

#set_property PACKAGE_PIN H20 [get_ports Bank[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports Bank[1]]
#set_property PACKAGE_PIN J19 [get_ports Bank[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports Bank[0]]

#set_property PACKAGE_PIN J22 [get_ports Address[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[12]]
#set_property PACKAGE_PIN J15 [get_ports Address[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[11]]
#set_property PACKAGE_PIN K21 [get_ports Address[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[10]]
#set_property PACKAGE_PIN H15 [get_ports Address[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[9]]
#set_property PACKAGE_PIN G18 [get_ports Address[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[8]]
#set_property PACKAGE_PIN G17 [get_ports Address[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[7]]
#set_property PACKAGE_PIN H14 [get_ports Address[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[6]]
#set_property PACKAGE_PIN J14 [get_ports Address[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[5]]
#set_property PACKAGE_PIN G16 [get_ports Address[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[4]]
#set_property PACKAGE_PIN J20 [get_ports Address[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[3]]
#set_property PACKAGE_PIN J21 [get_ports Address[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[2]]
#set_property PACKAGE_PIN K22 [get_ports Address[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[1]]
#set_property PACKAGE_PIN H19 [get_ports Address[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports Address[0]]

#set_property PACKAGE_PIN M13 [get_ports Data[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[0]]
#set_property PACKAGE_PIN L13 [get_ports Data[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[1]]
#set_property PACKAGE_PIN L16 [get_ports Data[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[2]]
#set_property PACKAGE_PIN M15 [get_ports Data[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[3]]
#set_property PACKAGE_PIN K16 [get_ports Data[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[4]]
#set_property PACKAGE_PIN L14 [get_ports Data[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[5]]
#set_property PACKAGE_PIN K17 [get_ports Data[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[6]]
#set_property PACKAGE_PIN K14 [get_ports Data[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[7]]
#set_property PACKAGE_PIN M21 [get_ports Data[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[8]]
#set_property PACKAGE_PIN M22 [get_ports Data[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[9]]
#set_property PACKAGE_PIN N19 [get_ports Data[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[10]]
#set_property PACKAGE_PIN M20 [get_ports Data[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[11]]
#set_property PACKAGE_PIN N18 [get_ports Data[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[12]]
#set_property PACKAGE_PIN N20 [get_ports Data[13]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[13]]
#set_property PACKAGE_PIN M16 [get_ports Data[14]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[14]]
#set_property PACKAGE_PIN L15 [get_ports Data[15]]
#set_property IOSTANDARD LVCMOS33 [get_ports Data[15]]

#UART
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports esp_rx_i]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports esp_tx_o]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports esp_cts_n_o]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports esp_gpio0_io]
set_property -dict {PACKAGE_PIN L6 IOSTANDARD LVCMOS33} [get_ports esp_rtr_n_i]


#I2C
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports i2c_scl_io]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports i2c_sda_io]

##MIDI
#set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS33} [get_ports midi_clkbd]
#set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports midi_wsbd]
#set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS33} [get_ports midi_dabd]
#set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports midi_out]

##EDGE
#set_property PACKAGE_PIN R2 [get_ports edge_A15]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A15]
#set_property PACKAGE_PIN P6 [get_ports edge_A14]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A14]
#set_property PACKAGE_PIN P5 [get_ports edge_A12]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A12]
#set_property PACKAGE_PIN J6 [get_ports edge_CLK]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_CLK]
#set_property PACKAGE_PIN K3 [get_ports edge_A0]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A0]
#set_property PACKAGE_PIN L3 [get_ports edge_A1]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A1]
#set_property PACKAGE_PIN J4 [get_ports edge_A2]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A2]
#set_property PACKAGE_PIN G3 [get_ports edge_A3]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A3]
#set_property PACKAGE_PIN H3 [get_ports edge_INT]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_INT]
#set_property PACKAGE_PIN J5 [get_ports edge_NMI]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_NMI]
#set_property PACKAGE_PIN H2 [get_ports edge_MREQ]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_MREQ]
#set_property PACKAGE_PIN G4 [get_ports edge_IORQ]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_IORQ]
#set_property PACKAGE_PIN K1 [get_ports edge_RD]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_RD]
#set_property PACKAGE_PIN B22 [get_ports edge_A10]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A10]
##set_property IOSTANDARD LVCMOS25 [get_ports edge_A10]
#set_property PACKAGE_PIN E2 [get_ports edge_RESET]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_RESET]
#set_property PACKAGE_PIN H4 [get_ports edge_WR]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_WR]
#set_property PACKAGE_PIN E3 [get_ports edge_A7]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A7]
#set_property PACKAGE_PIN F1 [get_ports edge_A6]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A6]
#set_property PACKAGE_PIN F3 [get_ports edge_A5]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A5]
#set_property PACKAGE_PIN K2 [get_ports edge_M1]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_M1]
#set_property PACKAGE_PIN M2 [get_ports edge_A4]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A4]
#set_property PACKAGE_PIN M3 [get_ports edge_ROMCS]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_ROMCS]
#set_property PACKAGE_PIN B2 [get_ports edge_A8]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A8]
#set_property PACKAGE_PIN R3 [get_ports edge_A13]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A13]
#set_property PACKAGE_PIN F4 [get_ports edge_A9]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A9]
#set_property PACKAGE_PIN C2 [get_ports edge_A11]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_A11]
#set_property PACKAGE_PIN T21 [get_ports edge_D0]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D0]
#set_property PACKAGE_PIN M17 [get_ports edge_D1]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D1]
#set_property PACKAGE_PIN J16 [get_ports edge_D2]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D2]
#set_property PACKAGE_PIN L19 [get_ports edge_D3]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D3]
#set_property PACKAGE_PIN K18 [get_ports edge_D4]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D4]
#set_property PACKAGE_PIN L20 [get_ports edge_D5]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D5]
#set_property PACKAGE_PIN K13 [get_ports edge_D6]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D6]
#set_property PACKAGE_PIN U21 [get_ports edge_D7]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_D7]
#set_property PACKAGE_PIN J1 [get_ports edge_HALT]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_HALT]
#set_property PACKAGE_PIN G13 [get_ports edge_BUSRQ]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_BUSRQ]
#set_property PACKAGE_PIN D2 [get_ports edge_BUSAK]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_BUSAK]
#set_property PACKAGE_PIN H17 [get_ports edge_REFRESH]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_REFRESH]
#set_property PACKAGE_PIN H18 [get_ports edge_WAIT]
#set_property IOSTANDARD LVCMOS33 [get_ports edge_WAIT]

